### ISSUE TITLE
yay for glimmer-gtk \o/

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-gtk#1]
Hey there Andy,

I just noticed the gtk-branch here; I assume it's fairly new. If so that's cool - feels like 
fresh breeze code! \o/

I don't want to add open issues so this was just a cheering ASCII guy \o/ to show 
epicness in glimmer. I think one issue may be that many ruby users still don't 
know glimmer (issue in the sense that if people don't know of alternatives, they
may look for other projects/languages, which is kind of bad, since they contribute
for other languages rather than language xyz, thus fewer projects for language
xyz and so on and so forth. And the age-situation too, e. g. when young folks
go to other languages ... but I don't want to go into hypothetical land here, just
a loose comment it was meant to be).

I kind of dream of a DSL where we can sort of unify TONS of different GUIs,
toolsets as well as www-related aspects. Kind of like what rack is for
web-frameworks, a meta-plug-in or however you want to call it.

Anyway, this is just a cheers and thumbs up issue, so I'll close it myself. :)

**Comment by AndyObtiva** [comment]
Thank you.

I think Glimmer’s most important goals are high productivity and simple maintainability. Unification is not a very important concern by comparison. It is good to have multiple different tools available to be able to use the right tool for every varying job. Options are helpful to have. 

 Cheers!
