### ISSUE TITLE
Compile error on installation of glimmer-dsl-gtk

### ISSUE THREAD

**Issue by bill644** [AndyObtiva/glimmer-dsl-gtk#11]
Error occurs in compiling rbglib_bookmarkfile.c (following a warning compiling glib-enum-types.c), Log file is attached.

current directory: /var/lib/gems/3.2.0/gems/glib2-3.4.9/ext/glib2
/usr/bin/ruby3.2 -I/usr/lib/ruby/vendor_ruby extconf.rb
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Waggregate-return option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... no
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... no
checking for -Wpointer-arith option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... no
checking for -Wunsafe-loop-optimizations option to compiler... yes
checking for -Wwrite-strings option to compiler... yes
checking for Homebrew... no
checking for gobject-2.0 version (>= 2.12.0)... yes (2.80.0)
checking for gthread-2.0... yes (2.80.0)
checking for unistd.h... yes
checking for io.h... no
checking for rb_check_array_type() in ruby.h... yes
checking for rb_check_hash_type() in ruby.h... yes
checking for rb_exec_recursive() in ruby.h... yes
checking for rb_errinfo() in ruby.h... yes
checking for rb_thread_call_without_gvl() in ruby.h... yes
checking for ruby_native_thread_p() in ruby.h... yes
checking for rb_thread_call_with_gvl() in ruby.h... yes
checking for rb_gc_register_mark_object() in ruby.h... yes
checking for rb_exc_new_str() in ruby.h... yes
checking for rb_enc_str_new_static() in ruby.h... yes
checking for curr_thread in ruby.h,node.h... no
checking for rb_curr_thread in ruby.h,node.h... no
creating ruby-glib2.pc
creating glib-enum-types.c
creating glib-enum-types.h
creating Makefile

current directory: /var/lib/gems/3.2.0/gems/glib2-3.4.9/ext/glib2
make DESTDIR\= sitearchdir\=./.gem.20241216-52958-vdi3z1 sitelibdir\=./.gem.20241216-52958-vdi3z1 clean

current directory: /var/lib/gems/3.2.0/gems/glib2-3.4.9/ext/glib2
make DESTDIR\= sitearchdir\=./.gem.20241216-52958-vdi3z1 sitelibdir\=./.gem.20241216-52958-vdi3z1
compiling glib-enum-types.c
glib-enum-types.c: In function ‘g_spawn_error_get_type’:
glib-enum-types.c:652:7: warning: ‘G_SPAWN_ERROR_2BIG’ is deprecated: Use 'G_SPAWN_ERROR_TOO_BIG' instead [-Wdeprecated-declarations]
  652 |       { G_SPAWN_ERROR_2BIG, "G_SPAWN_ERROR_2BIG", "2big" },
      |       ^
In file included from /usr/include/glib-2.0/glib.h:84,
                 from /usr/include/glib-2.0/gobject/gbinding.h:30,
                 from /usr/include/glib-2.0/glib-object.h:24,
                 from rbgobject.h:24,
                 from rbgprivate.h:32,
                 from glib-enum-types.c:4:
/usr/include/glib-2.0/glib/gspawn.h:78:3: note: declared here
   78 |   G_SPAWN_ERROR_2BIG GLIB_DEPRECATED_ENUMERATOR_IN_2_32_FOR(G_SPAWN_ERROR_TOO_BIG) = G_SPAWN_ERROR_TOO_BIG,
      |   ^~~~~~~~~~~~~~~~~~
compiling rbglib-bytes.c
compiling rbglib-gc.c
compiling rbglib-variant-type.c
compiling rbglib-variant.c
compiling rbglib.c
compiling rbglib_bookmarkfile.c
rbglib_bookmarkfile.c:39:1: error: static declaration of ‘g_bookmark_file_get_type’ follows non-static declaration
   39 | g_bookmark_file_get_type(void)
      | ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gboxed.h:29,
                 from /usr/include/glib-2.0/gobject/gobject.h:31,
                 from /usr/include/glib-2.0/gobject/gbinding.h:31,
                 from /usr/include/glib-2.0/glib-object.h:24,
                 from rbgobject.h:24,
                 from rbgprivate.h:32,
                 from rbglib_bookmarkfile.c:22:
/usr/include/glib-2.0/gobject/glib-types.h:438:9: note: previous declaration of ‘g_bookmark_file_get_type’ with type ‘GType(void)’ {aka ‘long unsigned int(void)’}
  438 | GType   g_bookmark_file_get_type   (void) G_GNUC_CONST;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
rbglib_bookmarkfile.c:50: warning: "G_TYPE_BOOKMARK_FILE" redefined
   50 | #define G_TYPE_BOOKMARK_FILE (g_bookmark_file_get_type())
      | 
/usr/include/glib-2.0/gobject/glib-types.h:337: note: this is the location of the previous definition
  337 | #define G_TYPE_BOOKMARK_FILE (g_bookmark_file_get_type ())
      | 
make: *** [Makefile:248: rbglib_bookmarkfile.o] Error 1

make failed, exit code 2

**Comment by AndyObtiva** [comment]
What version of Ruby are you running? This gem was developed when Ruby 3.1 was the latest version. It might have issues with newer Rubies. I would regress my Ruby to 3.1 (or even to an older version like 3.0) before trying to install the gem.

There are plans to update the gem to support GTK 4, which should run on newer Rubies. Until that happens, I recommend regressing to an older version of Ruby if that works, or exploring other Glimmer DSLs temporarily.

**Comment by bill644** [comment]
Thanks for the response. My Ruby version is 3.2.3.

However, since posting the issue, I've decided that Glimmer is probably
overkill for the project I'm working on and have written a small Ruby
extension to meet my needs. So I won't be fussing any more with my
installation issue.

-Bill
