### ISSUE TITLE
Tetris variant in glimmer-dsl-gtk?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-gtk#2]
Hey there Andy,

I know you have been busy via perfect-shape and you seem to look at fxruby too - not that I would ever admit to
github-stalking ... :D

I recently played tetris via glimmer-dsl-libui and it works fine on linux. (I haven't yet tested on windows, as that is
on a computer to the other side of the room, with less comfortable seating possibilities. Will test at a later time :P )

Would it be possible to add tetris to glimmer-dsl-gtk, if it is not too much work? I haven't dived into the glimmer-tetris
code base but tetris seems to be relevant to glimmer if only as demo purpose (e. g. your other github repository
there https://github.com/AndyObtiva/glimmer_tetris). If you "get to that eventually" then just please disregard the
issue here. My assumption here is that since libui+tetris on linux works, then perhaps the underlying code base is
super simple to adjust to glimmer-dsl-gtk as well, since libui on linux (if I am not mistaken) simply uses gtk too,
so that should hopefully not be too much work. Thank you for reading, glimmer on!

**Comment by AndyObtiva** [comment]
I am done with [Perfect Shape](https://github.com/AndyObtiva/perfect-shape) for the time being. [Version 1.0.0](https://github.com/AndyObtiva/perfect-shape) was released!

I got a [basic Tetris working in Glimmer DSL for GTK](https://github.com/AndyObtiva/glimmer-dsl-gtk#tetris) after I added support for cairo drawing declaratively (as demonstrated by [Hello, Drawing Area!](https://github.com/AndyObtiva/glimmer-dsl-gtk#hello-drawing-area)):

Linux | Mac | Windows
------|-----|--------
![tetris](https://github.com/AndyObtiva/glimmer-dsl-gtk/raw/master/screenshots/glimmer-dsl-gtk-linux-tetris.png) | ![tetris](https://github.com/AndyObtiva/glimmer-dsl-gtk/raw/master//screenshots/glimmer-dsl-gtk-mac-tetris.png) | ![tetris](https://github.com/AndyObtiva/glimmer-dsl-gtk/raw/master//screenshots/glimmer-dsl-gtk-windows-tetris.png)

**Comment by AndyObtiva** [comment]
I finished implementing Tetris with the Score Board, Menu Bar, and Next Tetromino Preview.

i am closing this issue as a result.

Cheers!
