### ISSUE TITLE
Tetris example: two minor things

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-gtk#4]
Heya Andy,

I just tried the tetris.rb example. It works.

I get one warning which is not important but I mention it still:

    glimmer-dsl-gtk-0.0.8/lib/glimmer/gtk/widget_proxy.rb:192:in `new': 'Gtk::MessageDialog#initialize(parent, flags, type, buttons_type, message)' style has been deprecated. Use 'Gtk::MessageDialog#initialize(:parent => nil, :flags => 0, :type => :info, :buttons => :ok, :message => "")' style.

It should be easy to fix though, e. g. just adding parent: and the other needed components.

The second thing is that when the game is over, a pop-up shows up showing the score. Meanwhile, though, a new
game is automatically started, which means that the pop-up shown interferes a bit visually. There are many ways
this could be changed, but I would propose that the new game is only started when the user clicks away that pop
up. (And just as I type this, I discovered a third tiny bug - the new game keeps on running, and when you lose it,
another popup shows up, so now I have three pop-ups so far :D - I guess if I keep it running it will keep on spawning
popups, which is quite funny. I think the simplest fix is to probably delay starting a new game until the pop up 
widget is clicked away).

PS: I am testing on tetris as the main game implementation for all of glimmer there. :D (I forgot whether I tested the
opal-tetris yet... last time I had issues with opal itself, hopefully that resolves eventually. Would be cool to make 
games in glimmer and have them "just work (tm)" no matter the GUI/platform).

**Comment by AndyObtiva** [comment]
Actually, you can test [Glimmer Tetris on the web](https://github.com/AndyObtiva/glimmer-dsl-opal#tetris) without installing Opal if you like. 

All [Glimmer DSL for Opal samples](https://github.com/AndyObtiva/glimmer-dsl-opal#samples) are hosted on Heroku (click on the link below, scroll down to find and click Tetris, and be patient while it loads as the screen will look frozen until Tetris starts since no progress bar has been implemented):

https://sample-glimmer-dsl-opal-app.herokuapp.com

Your feedback for Glimmer Tetris in GTK is noted. I will close this issue once it is implemented.

**Comment by AndyObtiva** [comment]
OK, I just made a release of [Glimmer DSL for GTK v0.0.9](https://rubygems.org/gems/glimmer-dsl-gtk/versions/0.0.9) addressing your issues, including the latest changes to Tetris that you asked about for Glimmer DSL for LibUI like making the Next Tetromino Block Preview optional and having a Speed option. Changes are:
- Add the text "Next" before the Next Tetromino Preview area
- Tetris "Show Next Block Preview" menu item under "View" menu
- Tetris "Speed" menu
- Fix Tetris Help menu (was called Options by mistake)
- Fix issue with Tetris game restarting immediately on game over
- Fix issue with Tetris not accelerating upon level ups
- Fix warning message: glimmer-dsl-gtk-0.0.8/lib/glimmer/gtk/widget_proxy.rb:192:in `new': 'Gtk::MessageDialog#initialize(parent, flags, type, buttons_type, message)' style has been deprecated. Use 'Gtk::MessageDialog#initialize(:parent => nil, :flags => 0, :type => :info, :buttons => :ok, :message => "")' style.
- Fix warning message: Attempting to add a widget with type GtkMenu to a container of type GtkMenuItem, but the widget is already inside a container of type GtkWindow, please remove the widget from its existing container first.

Linux | Mac | Windows
------|-----|--------
![tetris](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-gtk/master/screenshots/glimmer-dsl-gtk-linux-tetris.png) | ![tetris](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-gtk/master/screenshots/glimmer-dsl-gtk-mac-tetris.png) | ![tetris](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-gtk/master/screenshots/glimmer-dsl-gtk-windows-tetris.png)

Cheers!
